import { Dispatch, SetStateAction } from 'react';
import { DEFAULT_OFFER_SCHEMA } from '../lib/constants';
import { formatTokenAmount } from '../lib/tokens';
import { OrderData } from '../lib/useOrder';
import { OfferForm } from './forms/AutoGeneratedForm';
import { SimpleOfferForm } from './forms/DefaultForm';

export function CheckoutForm(props: {
  order: OrderData;
  setOfferData: Dispatch<SetStateAction<any>>;
  offerData: any;
  setValidChecker: (_: () => Boolean) => void;
}) {
  const price = formatTokenAmount(props.order.priceSuggested, props.order.tokensSuggested[0]);;
  return (
    <>
      <div>
        {props.order.offerSchemaUri &&
        props.order.offerSchemaUri.replace('ipfs://', '') !=
          DEFAULT_OFFER_SCHEMA ? (
          <OfferForm
            schema={props.order.offerSchema}
            setOfferData={props.setOfferData}
            offerData={props.offerData}
            price={price}
            setValidChecker={props.setValidChecker}
            symbol={props.order.tokensSuggested[0].symbol}
          />
        ) : (
          <SimpleOfferForm
            setOfferData={props.setOfferData}
            offerData={props.offerData}
            price={price}
            setValidChecker={props.setValidChecker}
            symbol={props.order.tokensSuggested[0].symbol}
          />
        )}
      </div>
    </>
  );
}
